version: '3'

services:
 db: 
   image: postgres
   volumes:
     - ./db:/var/lib/postgresql/data
   environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: password
     POSTGRES_DB: backend_development
   ports:
     - "5432:5432"
   restart: always
   networks:
      - test_net
 api:
    container_name: rails-api
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails db:seed && bundle exec rails s -p 8000 -b '0.0.0.0'"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/backend_development
      RAILS_ENV: development
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
    networks:
      - test_net
 wui:
   container_name: next-app
   build:
      context: ./client
      dockerfile: Dockerfile
   volumes:
     - ./client:/app
   restart: always
   ports:
      - 3000:3000
   depends_on:
      - api
   networks:
     - test_net
    
networks:
  test_net:
    driver: bridge
    attachable: true
      
   