version: '3'

services:
 db: 
   image: postgres
   volumes:
     - ./db:/var/lib/postgresql/data
   environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: password
     POSTGRES_DB: backend_development
   working_dir: /backend
   ports:
     - "5436:5432"
   restart: always
   networks:
      - teebay_network
 api:
    container_name: api
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -p 8000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/backend_development
      RAILS_ENV: development
    volumes:
      - ./backend:/api
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
    networks:
      - teebay_network
 wui:
   container_name: wui
   build:
      context: ./client
      dockerfile: Dockerfile
   command: sh -c "npm install && npm run dev"
   volumes:
     - ./client:/client
   environment:
     NODE_ENV: development
     POSTGRES_PASSWORD: password
   restart: always
   ports:
      - "3000:3000"
   depends_on:
      - api
   networks:
     - teebay_network
    
networks:
  teebay_network:
    driver: bridge
    attachable: true
      
   