# Generated by Django 4.0.1 on 2022-01-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teebaykend', '0004_alter_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
